server:
    port: 8071

spring:
    application:
          name: sedSvcEmuBackEnd3.ext
    devtools:
        add-properties: false
        livereload:
            port: 35730
            enabled: false
    kafka:
        consumer:
            bootstrap-servers: localhost:9092
            group-id: group_id
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        producer:
            #?? acks
            bootstrap-servers: localhost:9092
            client-id: web-send-requests-104

#    boot:
#        admin:
#            client:
#                url: http://localhost:8071/admin
#            enable: true
#            context-path: /admin
#            auto-registration: true
#            username: admin
#            password: 777


logging:
    config: "config/log4j2.yaml"

sedSvc:
    simpleDebug: true
    cache-dir: D:\MyDocsTeng-workDoc\github-TengedSedsvcEmu\sedsvc-emu-via-kafka\_work-cache
    topic-rcpt: top-reg-2345
    topic-from: top-from-2256
